### ISSUE TITLE
node-gyp build and npm install both fail

### ISSUE THREAD

**Issue by xthdraft** [magiclen/node-stringbuilder#1]
I've tried to install using npm install node-stringbuilder and also I've tried building with node-gyp using  node-gyp configure build.

I'm using npm@6.4.1 and node@v10.12.0
Not sure if that is an issue there.

In both cases the builds fail with these messages:

c:\node-stringbuilder\node_modules\node-stringbuilder\src\node-stringbuilder.c(6): warning C4005: 'max': macro redefinition [c:\node-stringbuilder\node_modules\node-stringbuilder\build\node-stringbuilder.vcxpro
j]
  c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\stdlib.h(1289): note: see previous definition of 'max'

c:\node-stringbuilder\node_modules\node-stringbuilder\src\node-stringbuilder.c(1315): error C2057: expected constant expression [c:\node-stringbuilder\node_modules\node-stringbuilder\build\node-stringbuilder.vc
xproj]
c:\node-stringbuilder\node_modules\node-stringbuilder\src\node-stringbuilder.c(1315): error C2466: cannot allocate an array of constant size 0 [c:\node-stringbuilder\node_modules\node-stringbuilder\build\node-s
tringbuilder.vcxproj]
c:\node-stringbuilder\node_modules\node-stringbuilder\src\node-stringbuilder.c(1315): error C2133: 'utf8Data': unknown size [c:\node-stringbuilder\node_modules\node-stringbuilder\build\node-stringbuilder.vcxpro
j]

**Comment by magiclen** [comment]
I've found and fixed an allocation bug, please use node 8.6+ to try again.

**Comment by xthdraft** [comment]
Hello Ron.

It works now after changing the 2 lines concerning malloc.

The warning concerning redefinition of "max" still exists: probably not too
important.

 warning C4005: 'max': macro redefinition
[c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
 c:\program files (x86)\windows
kits\10\include\10.0.17134.0\ucrt\stdlib.h(1289): note: see previous
definition of 'max'

The electron build also works using this instruction:
node-gyp rebuild --target=3.0.6 --arch=x64 --dist-url=
https://atom.io/download/electron

There were a bunch of warnings concerning type conversions:

c:\node-stringbuilder\src\node-stringbuilder.c(6): warning C4005: 'max':
macro redefinition [c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\program files (x86)\windows
kits\10\include\10.0.17134.0\ucrt\stdlib.h(1289): note: see previous
definition of 'max'
c:\node-stringbuilder\src\node-stringbuilder.c(73): warning C4244: '=':
conversion from 'int64_t' to 'uint32_t', possible loss of data
[c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(133): warning C4244: '=':
conversion from 'int64_t' to 'uint32_t', possible loss of data
[c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(250): warning C4244: '=':
conversion from 'int64_t' to 'uint32_t', possible loss of data
[c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(489): warning C4244:
'function': conversion from 'int64_t' to 'double', possible loss of data
[c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(848): warning C4244:
'function': conversion from 'int64_t' to 'double', possible loss of data
[c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(851): warning C4244:
'function': conversion from 'int64_t' to 'double', possible loss of data
[c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(848): warning C4244:
'initializing': conversion from 'double' to 'int64_t', possible loss of
data [c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(851): warning C4244:
'initializing': conversion from 'double' to 'int64_t', possible loss of
data [c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(1188): warning C4244:
'function': conversion from 'int64_t' to 'double', possible loss of data
[c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(1191): warning C4244:
'function': conversion from 'int64_t' to 'double', possible loss of data
[c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(1188): warning C4244:
'initializing': conversion from 'double' to 'int64_t', possible loss of
data [c:\node-stringbuilder\build\node-stringbuilder.vcxproj]
c:\node-stringbuilder\src\node-stringbuilder.c(1191): warning C4244:
'initializing': conversion from 'double' to 'int64_t', possible loss of
data [c:\node-stringbuilder\build\node-stringbuilder.vcxproj]

My app called the module successfully:

var StringBuilder =
require('c:/node-stringbuilder/build/Release/node-stringbuilder.node');

My app ran the module successfully:

var sb = StringBuilder.from('First', 4096);
sb.insert('string');
sb.toString()  // returned "stringFirst"

So all good.

Thank you so much.  I'll keep you informed of any issues as I test the
module further in my app.

Should I post this in your issue tracker on github?

- Eamon

**Comment by magiclen** [comment]
Yeah, it takes time to fix the type warnings. Please file a new issue.

**Comment by xthdraft** [comment]
Since it seems fixed, you could probably close that issue.
